### ISSUE TITLE
why does it require a user ID to init?

### ISSUE THREAD

**Issue by dcsan** [crookedneighbor/amplitude#13]
i was looking at adding this to a server app

```
var amplitude = new Amplitude('api-token', { user_id: 'some-user-id' });
```

but with that requirement it seems I would have to track a list of amplitude objects for each user on the system, and reuse them?

since the server is handling lots of users obviously, this seems weird - is this because it's a client side SDK that you've wrapped (which assumes just one user for a session)

it would be **much** more convenient if we could just send `trackEvent( userId, data )`
and not have to track and reuse the correct amplitude instances per user in order to send events.

another way is to create (init) a new amplitude object every time I want to track an event, but that seems very wasteful/leaky too.

Am I missing something in how to use this wrapper?

**Comment by crookedneighbor** [comment]
The module is a wrapper around the [Amplitude http api](https://amplitude.zendesk.com/hc/en-us/articles/204771828-HTTP-API) and it's specified in the documentation that either a `user_id` or a `device_id` are required.

If you look at the [constructor code](https://github.com/crookedneighbor/amplitude/blob/master/src/amplitude.js#L4-L20) you'll see that there's nothing stopping you from initializing the module without a user/device id. All the user/device id does is provide a default value when using the track method. If you don't provide a default value, you'll need to supply `user_id` or `device_id` as part of the object passed into track.

You're right though that the readme does not make that clear. I'm going to leave this issue open until I adjust the Readme to display an example without passing in a user/device id up front. If you'd like to submit a pull request, feel free.

**Comment by crookedneighbor** [comment]
The documentation should now be up to date. Also, I've published [a new major version](https://github.com/crookedneighbor/amplitude/releases/tag/v3.0.0).

Let me know if you have additional questions.
