### ISSUE TITLE
track() uses POST, but puts all data in the query string

### ISSUE THREAD

**Issue by jnorris441** [crookedneighbor/amplitude#27]
According to Amplitude they don't have a limit on the data you can pass....but if all properties are in the query string you can hit a limit.

Is there a reason the data isn't sent as POST fields?

**Comment by crookedneighbor** [comment]
The last time I tried, the request didn't work with a post body. (Might have been a bug that has since been resolved). If you submit a PR that works, I'll review and merge it in.

**Comment by jnorris441** [comment]
OK

https://github.com/crookedneighbor/amplitude/pull/28

**Comment by crookedneighbor** [comment]
Closed with #28
