### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by michaelvol** [crookedneighbor/amplitude#48]
Great work and very useful, thank you!

The Amplitude identify API supports operations like $add, $append, etc.
Looks like it's possible to use the library for these operations also.

        var event = {
            userId: userid,
            userProperties: {
                $set: {
                    firstName: 'firstName',
                    lastName: 'lastName'
                },
                $add: { counter: 1 }
            }
        };
        amplitude.identify(event);

**Comment by crookedneighbor** [comment]
Would you like to open a PR?

**Comment by michaelvol** [comment]
Sure (https://github.com/crookedneighbor/amplitude/pull/49)

**Comment by crookedneighbor** [comment]
Closed with https://github.com/crookedneighbor/amplitude/pull/49
