### ISSUE TITLE
Support connection keep-alive

### ISSUE THREAD

**Issue by michaelvol** [crookedneighbor/amplitude#50]
It can be useful to pass an HttpsAgent to the constructor to control connection keep-alive. 
It can significantly reduce the time for each request, especially if not sending in batches. 

Does it make sense to you adding this feature?

**Comment by crookedneighbor** [comment]
Hmm.... I'd want to see the implementation to know for sure.

**Comment by michaelvol** [comment]
It can be set by calling `agent()` for a request.
The implementation would look like this:
[set-agent-patch.txt](https://github.com/crookedneighbor/amplitude/files/1106736/set-agent-patch.txt)

**Comment by crookedneighbor** [comment]
Looking for a new maintainer for this project. Going to close this issue, but if you're interested in taking over the project, comment here or open a new issue.
