### ISSUE TITLE
Can't detect default data events 

### ISSUE THREAD

**Issue by ardname** [crookedneighbor/amplitude#51]
Hello!

Why the module can't detect this default data?
http://joxi.ru/DmBgQVLTNNREx2

If i using Javascript library or Android SDK for Amplitude, no problem at all, but if i am trying to use this node.js module i can't see that data.

**Comment by crookedneighbor** [comment]
This module is meant to be a thin wrapper around the amplitude API. So it doesn't do any browser or geo-location detection. This module is primarily used on the server, where that information can't be easily parsed anyway. (depending on your server framework though, you could get some of it from request headers and pass that data into the module)

If you need those things to be done by default, it's probably better to use Amplitude's official SDKs.

Going to close this, but if I misunderstood your question, feel free to comment.
