### ISSUE TITLE
Return empty

### ISSUE THREAD

**Issue by josebispo** [crookedneighbor/amplitude#67]
My code return empty, when I use the segmentation return data, 

 amplitude.track({
        event_type: 'Enter Project',
    }).then(function (result) {

        console.log(result);
            return response.status(200).json(result);

        }).catch(function (error) {
        return response.status(400).json(error);
    });

Ca I pass user_id in eventSegmentation?

**Comment by crookedneighbor** [comment]
This SDK is just a light wrapper around the Amplitude API. Here's the section on event segmentation: https://amplitude.zendesk.com/hc/en-us/articles/205469748-Dashboard-Rest-API-Export-Amplitude-Dashboard-Data#event-segmentation 

Don't see a spot to enter a user id, but feel free to dig through the docs.

**Comment by josebispo** [comment]
Hi @crookedneighbor, 

I saw the query documentation and created the right parameters now it's working,

Best regards
