### ISSUE TITLE
Publish latest version to NPM

### ISSUE THREAD

**Issue by ondrej** [crookedneighbor/amplitude#77]
Blade, any way you could publish a new version of the package to NPM with an updated package.json for superagent? The currently published version still references ^3.3.1 which produces the follow warning on install:

npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.

The one in GitHub references ^5.0.7.

**Comment by crookedneighbor** [comment]
Sure. Just published v4.0.0

See https://github.com/crookedneighbor/amplitude/releases/tag/v4.0.0 for release notes
