### ISSUE TITLE
Support for Amplitude HTTP API v2

### ISSUE THREAD

**Issue by harytkon** [crookedneighbor/amplitude#79]
Amplitude deprecates HTTP API **v1**.
https://help.amplitude.com/hc/en-us/articles/360032842391-HTTP-API-V2

Any plans to provide support for HTTP API **v2**?

**Comment by crookedneighbor** [comment]
I no longer use Amplitude, so I'm not going to implement this. 

I'm going to update the README to say this project is looking for a maintainer. I can transfer ownership of the npm package to the new maintainer when a new one is found.

**Comment by crookedneighbor** [comment]
Looking for a new maintainer for this project. Going to close this issue, but if you're interested in taking over the project, comment here or open a new issue.

**Comment by geoffdutton** [comment]
I would be willing to over the project. We use it extensively at my company.
