### ISSUE TITLE
Open to taking over as a maintainer

### ISSUE THREAD

**Issue by geoffdutton** [crookedneighbor/amplitude#83]
My company uses this pretty extensively, so I'd be happy to spend time to keep it updated and moving forward.

@crookedneighbor Let me know what you think/have questions/etc.

**Comment by crookedneighbor** [comment]
Send me your npm username.

**Comment by geoffdutton** [comment]
https://www.npmjs.com/~dutton

**Comment by crookedneighbor** [comment]
I’ve added you as a maintainer. Post a link to your Github fork, and I’ll link to it from this repo’s readme and then archive it. 

Go ahead and update the package.json on your repo with the new repo location and publish a new version, then I’ll remove myself from the module.

**Comment by geoffdutton** [comment]
Here's my fork with the updates and the patch version incremented: https://github.com/geoffdutton/amplitude

NPM is telling me I don't permission to publish to "amplitude". Did you set write access ?

**Comment by crookedneighbor** [comment]
![Screen Shot 2020-01-31 at 10 02 34 AM](https://user-images.githubusercontent.com/2916945/73554170-d4e27d80-4410-11ea-851a-9be08ba9acdb.png)

As long as this is you, you should have write access.

**Comment by geoffdutton** [comment]
I tried logging out and logging back it, and now it worked: https://www.npmjs.com/package/amplitude/v/4.0.1
